test: "Hallo"

filetypes:
  .jpg: 
    name: IMG_{year:04d}{month:02d}{day:02d}_{hour:02d}{minute:02d}{second:02d}.jpg
    patterns:
      - msg: Yo
        pattern: !!str IMG_(\d{4})(\d{2})(\d{2})_(\d{2})(\d{2})(\d{2}).jpg
        groups: [year, month, day, hour, minute, second]
        strftime: IMG_%Y%m%d_%H%M%S.jpg
      - msg: Mo

strftime: "%d-%m-%Y %H:%M:%S"

library: ~/Photos
folder_pattern: ""