---
- name: "Bash | Copy .bashrc"
  ansible.builtin.copy:
    src: ".bashrc"
    dest: "{{ ansible_user_dir }}/.bashrc"
    mode: "0644"

- name: "Bash | Copy .profile"
  ansible.builtin.copy:
    src: ".profile"
    dest: "{{ ansible_user_dir }}/.profile"
    mode: "0644"

- name: "Bash | Copy custom bash config"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/"
    src: "bash"
    mode: "0644"
    directory_mode: "0755"
    force: true

- name: "Bash | Set default terminal"
  ansible.builtin.user:
    name: "{{ host_user }}"
    shell: /usr/bin/bash
  become: true

# - name: "Bash | Set private variables"
#   ansible.builtin.template:
#     dest: "{{ ansible_user_dir }}/.config/bash/.bash_private"
#     src: ".bash_private.j2"
#     mode: "0644"
#   no_log: true

# - name: "Bash | Copy Private Files"
#   ansible.builtin.lineinfile:
#     name: "~/.openai.apikey"
#     line: "{{ bash_private.OPENAI_KEY }}"
#     create: true
#     mode: "0600"
#     state: present

- name: "Bash | {{ ansible_distribution }} | Identify distribution config"
  ansible.builtin.stat:
    path: "{{ role_path }}/files/os/{{ ansible_distribution }}"
  register: bash_os_distribution_config

- name: "Bash | {{ ansible_os_family }} | Identify os family config"
  ansible.builtin.stat:
    path: "{{ role_path }}/files/os/{{ ansible_os_family }}"
  register: bash_os_family_config
  when: not bash_os_distribution_config.stat.exists

- name: "Bash | Calculate os config src"
  ansible.builtin.set_fact:
    bash_os_config: "{{ bash_os_distribution_config if bash_os_distribution_config.stat.exists else bash_os_family_config }}"

- name: "Bash | Copy custom bash config for os: {{ bash_os_config.stat.path | basename }}"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/bash/"
    src: "{{ bash_os_config.stat.path }}/"
    mode: "0644"
    force: true
  when:
    - bash_os_config is defined
    - bash_os_config.stat.exists