---
# - name: "[vscode] - Import RHEL family specifics"
#   ansible.builtin.import_tasks: redhat.yml
#   become: yes
#   when: ansible_os_family == 'RedHat'

- name: "[vscode] - Import Debian family specifics"
  ansible.builtin.import_tasks: debian.yml
  become: yes
  when: ansible_os_family == 'Debian'

- name: "[vscode] - Install extensions"
  ansible.builtin.shell: "code --force --install-extension {{ item }}"
  loop: "{{ vscode_extensions  }}"
  when: vscode_use_extensions is defined and vscode_use_extensions
  changed_when: False

- name: Create vscode config directory if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/Code/User"
    state: directory
    mode: "0750"
  when: vscode_use_config is defined and vscode_use_config

- name: "[vscode] - Ensure link settings.json"
  block:
    - name: "Check .bashrc status"
      stat:
        path: "{{ ansible_user_dir }}/.config/Code/User/settings.json"
      register: test

    - name: "Remove .bashrc if needed"
      file:
        path: "{{ ansible_user_dir }}/.config/Code/User/settings.json"
        state: absent
      when: test.stat.islnk is defined and test.stat.islnk == False

    - file:
        src: "{{ role_path }}/files/config/settings.json"
        path: "{{ ansible_user_dir }}/.config/Code/User/settings.json"
        state: link
