---
- name: "Qtile | Copy config folder"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/"
    src: "qtile"
    mode: "0644"
    directory_mode: "0755"
    force: true

- name: Give execute permissions autostart
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/qtile/scripts/autostart.sh"
    mode: '0755'