---
- name: "Qtile | Copy config folder"
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/qtile"
    src: "{{ role_path }}/files/qtile"
    state: link

- name: Give execute permissions autostart
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/qtile/scripts/autostart.sh"
    mode: '0755'
