---
- name: "[thorium] - Debian - Copy repo list"
  ansible.builtin.copy:
    src: thorium.list
    dest: /etc/apt/sources.list.d/thorium.list
    mode: '0644'

- name: "[thorium] - Debian - Update software cache for apt-get again"
  become: True
  ansible.builtin.apt:
    update_cache: yes
  changed_when: False

- name: "[thorium] - Debian - Install Thorium Browser"
  ansible.builtin.apt:
    name: thorium-browser
    state: present