# ./.tmuxinator.yml

name: cursus-do180
root: ~/Projects/cursus-openshiftlocal-101
windows:
  - editor:
      layout: main-horizontal
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - nvim .
        - bash
  - server:
      layout: main-horizontal
      panes:
        - mdbook serve
  - git:
      panes:
        - lazygit
