---
- name: "System | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: system_distribution_config

- name: "System | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: system_distribution_config.stat.exists

- name: Ensuring config directory
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory

- name: Ensuring .local/bin directory
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory

# - name: "System | Set hosts"
#   ansible.builtin.template:
#     dest: "/etc/hosts"
#     src: hosts.j2
#     mode: "0644"
#   become: true
