---
- name: "[xdg] - Ensure link .user-dirs.dirs"
  block:
    - name: "Check .user-dirs.dirs status"
      stat:
        path: "{{ ansible_user_dir }}/.config/user-dirs.dirs"
      register: test

    - name: "Remove .user-dirs.dirs if needed"
      file:
        path: "{{ ansible_user_dir }}/.config/user-dirs.dirs"
        state: absent
      when: test.stat.islnk is defined and test.stat.islnk == False

    - file:
        src: "{{ role_path }}/files/user-dirs.dirs"
        path: "{{ ansible_user_dir }}/.config/user-dirs.dirs"
        state: link

- name: "[xdg] - Ensure link user-dirs.locale"
  block:
    - name: "Check user-dirs.locale status"
      stat:
        path: "{{ ansible_user_dir }}/.config/user-dirs.locale"
      register: test

    - name: "Remove user-dirs.locale if needed"
      file:
        path: "{{ ansible_user_dir }}/.config/user-dirs.locale"
        state: absent
      when: test.stat.islnk is defined and test.stat.islnk == False

    - file:
        src: "{{ role_path }}/files/user-dirs.locale"
        path: "{{ ansible_user_dir }}/.config/user-dirs.locale"
        state: link
