---
- name: "[gtk] .gtkrc-2.0"
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.gtkrc-2.0"
    src: ".gtkrc-2.0.j2"

- name: Create gtk-3.0 config folder if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/gtk-3.0"
    state: directory
    mode: '0755'

- name: "[gtk] gtk3 settings.ini"
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.config/gtk-3.0/settings.ini"
    src: "settings.ini.j2"
