---
- name: Install nitrogen
  ansible.builtin.package:
    name:
      - nitrogen
    state: latest
  become: true

- name: Create nitrogen config folder if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/nitrogen"
    state: directory
    mode: '0755'

- name: Nitrogen - nitrogen.cfg
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.config/nitrogen/nitrogen.cfg"
    src: "nitrogen.cfg.j2"

- name: Nitrogen - bg-saved.cfg
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.config/nitrogen/bg-saved.cfg"
    src: "bg-saved.cfg.j2"
  register: background

- name: Nitrogen - Restore background
  ansible.builtin.command: nitrogen --restore
  when: background.changed
