---
- name: Install nitrogen
  ansible.builtin.package:
    name:
      - nitrogen
    state: latest
  become: yes

- name: Nitrogen - nitrogen.cfg
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.config/nitrogen/nitrogen.cfg"
    src: "nitrogen.cfg.j2"

- name: Nitrogen - bg-saved.cfg
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.config/nitrogen/bg-saved.cfg"
    src: "bg-saved.cfg.j2"
  register: background

- name: Nitrogen - Restore background
  command: nitrogen --restore
  when: background.changed