---
- name: "[rofi] - Ensure installed"
  package:
    name: rofi
    state: latest
  become: true

- name: "[rofi] - Ensure scripts are available in local bin folder"
  copy:
    dest: "{{ ansible_user_dir }}/.local/bin/"
    src: "scripts/"
    mode: 0755

- name: "[rofi] - Ensure config folder links to .config"
  file:
    src: "{{ role_path }}/files/config"
    path: "{{ ansible_user_dir }}/.config/rofi"
    state: link

