---
- name: Install pyenv
  ansible.builtin.import_role:
    name: staticdev.pyenv
  vars:
    pyenv_env: 'user'
    pyenv_path: "{{ ansible_env.HOME }}/.pyenv"
    pyenv_global: ["3.12.5"]
    pyenv_python_versions: ["3.11.6", "3.12.5"]
    pyenv_uninstall_python_w_wrong_configure_opts: false
